package io.paritytech.polkadotapp.feature_become_citizen_impl.domain.bot

enum class TattooBotState {
    INITIALIZING,
    OTHER_DIM_COMMITMENT,
    OTHER_DIM_IN_PROGRESS,
    TATTOO_SELECTION,
    WAITING_FOR_VIDEO_EVIDENCE,
    WAITING_FOR_PHOTO_EVIDENCE,
    WAITING_FOR_CONFIRMATION,
    EVIDENCES_CONFIRMED,
    REGISTERED_PERSON,
    UNRECOVERABLE_ERROR
}
